# -*- coding: utf-8 -*-
"""FizzBuzz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1du2LqR_MLozqRacYVeDnmgDxYBJ-I2pP

FizzBuzz
"""

for x in range(1,101):
  if(x%3 == 0 and x%7 == 0):
    x = "fizzbuzz"
  elif(x%3 == 0):
    x = "fizz"
  elif(x%7 == 0):
    x = "buzz"
  print(x)